"""Initial Migr

Revision ID: 13de6ec6a9b0
Revises: 981e080da75f
Create Date: 2018-06-27 12:51:37.857501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13de6ec6a9b0'
down_revision = '981e080da75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commentspromotion_user_id_fkey', 'commentspromotion', type_='foreignkey')
    op.drop_column('commentspromotion', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentspromotion', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('commentspromotion_user_id_fkey', 'commentspromotion', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
