"""n

Revision ID: 357f8ec75c08
Revises: 60490d8150fb
Create Date: 2018-06-28 09:55:10.662470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357f8ec75c08'
down_revision = '60490d8150fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unlike', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('likes_user_id_key', 'likes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('likes_user_id_key', 'likes', ['user_id'])
    op.drop_table('unlikes')
    # ### end Alembic commands ###
