"""njfk

Revision ID: 60490d8150fb
Revises: 8202ef94e0b2
Create Date: 2018-06-28 09:36:05.708969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60490d8150fb'
down_revision = '8202ef94e0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_id_key', 'likes', type_='unique')
    op.create_unique_constraint(None, 'likes', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    op.create_unique_constraint('likes_id_key', 'likes', ['id'])
    # ### end Alembic commands ###
