"""Initial

Revision ID: 7b5151481ba7
Revises: 90e12250c910
Create Date: 2018-06-27 15:17:26.556676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5151481ba7'
down_revision = '90e12250c910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commentsproduction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['production.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commentspick', sa.Column('pick_id', sa.Integer(), nullable=True))
    op.drop_constraint('commentspick_promotion_id_fkey', 'commentspick', type_='foreignkey')
    op.create_foreign_key(None, 'commentspick', 'pick', ['pick_id'], ['id'])
    op.drop_column('commentspick', 'promotion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentspick', sa.Column('promotion_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'commentspick', type_='foreignkey')
    op.create_foreign_key('commentspick_promotion_id_fkey', 'commentspick', 'pick', ['promotion_id'], ['id'])
    op.drop_column('commentspick', 'pick_id')
    op.drop_table('commentsproduction')
    # ### end Alembic commands ###
