"""Ini

Revision ID: 7bc6c08c6fbd
Revises: e6e538ddb02f
Create Date: 2018-06-28 08:44:09.861763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc6c08c6fbd'
down_revision = 'e6e538ddb02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('pick_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('production_id', sa.Integer(), nullable=True))
    op.add_column('likes', sa.Column('promotion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'likes', 'production', ['production_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'interview', ['interview_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'promotion', ['promotion_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'pick', ['pick_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'promotion_id')
    op.drop_column('likes', 'production_id')
    op.drop_column('likes', 'pick_id')
    op.drop_column('likes', 'interview_id')
    # ### end Alembic commands ###
