"""nj

Revision ID: 8202ef94e0b2
Revises: 5465512fd895
Create Date: 2018-06-28 09:32:52.547082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8202ef94e0b2'
down_revision = '5465512fd895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'likes', ['id'])
    op.drop_constraint('likes_production_id_fkey', 'likes', type_='foreignkey')
    op.drop_column('likes', 'production_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('production_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('likes_production_id_fkey', 'likes', 'production', ['production_id'], ['id'])
    op.drop_constraint(None, 'likes', type_='unique')
    # ### end Alembic commands ###
