"""Initial Mi

Revision ID: 96cc89f525cf
Revises: 13de6ec6a9b0
Create Date: 2018-06-27 13:03:39.687107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cc89f525cf'
down_revision = '13de6ec6a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentspromotion', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commentspromotion', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commentspromotion', type_='foreignkey')
    op.drop_column('commentspromotion', 'user_id')
    # ### end Alembic commands ###
