"""Initial Migr

Revision ID: 981e080da75f
Revises: b159d2ecab68
Create Date: 2018-06-27 12:44:59.982115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981e080da75f'
down_revision = 'b159d2ecab68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentspromotion', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commentspromotion', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commentspromotion', type_='foreignkey')
    op.drop_column('commentspromotion', 'user_id')
    # ### end Alembic commands ###
